//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PromoStudio.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string An_error_occurred_while_processing_your_request_period {
            get {
                return ResourceManager.GetString("An_error_occurred_while_processing_your_request_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add music &amp; voice.
        /// </summary>
        public static string BuildStep__Add_music_amp_voice {
            get {
                return ResourceManager.GetString("BuildStep__Add_music_amp_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your script.
        /// </summary>
        public static string BuildStep__Add_your_script {
            get {
                return ResourceManager.GetString("BuildStep__Add_your_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string BuildStep__Audio {
            get {
                return ResourceManager.GetString("BuildStep__Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding.
        /// </summary>
        public static string BuildStep__Branding {
            get {
                return ResourceManager.GetString("BuildStep__Branding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change logo.
        /// </summary>
        public static string BuildStep__Change_logo {
            get {
                return ResourceManager.GetString("BuildStep__Change_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change photo.
        /// </summary>
        public static string BuildStep__Change_photo {
            get {
                return ResourceManager.GetString("BuildStep__Change_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose logo.
        /// </summary>
        public static string BuildStep__Choose_logo {
            get {
                return ResourceManager.GetString("BuildStep__Choose_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose photo.
        /// </summary>
        public static string BuildStep__Choose_photo {
            get {
                return ResourceManager.GetString("BuildStep__Choose_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your background music track.
        /// </summary>
        public static string BuildStep__Choose_your_background_music_track {
            get {
                return ResourceManager.GetString("BuildStep__Choose_your_background_music_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your logo placements.
        /// </summary>
        public static string BuildStep__Choose_your_logo_placements {
            get {
                return ResourceManager.GetString("BuildStep__Choose_your_logo_placements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your template.
        /// </summary>
        public static string BuildStep__Choose_your_template {
            get {
                return ResourceManager.GetString("BuildStep__Choose_your_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your voiceover talent.
        /// </summary>
        public static string BuildStep__Choose_your_voiceover_talent {
            get {
                return ResourceManager.GetString("BuildStep__Choose_your_voiceover_talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the footage.
        /// </summary>
        public static string BuildStep__Customize_the_footage {
            get {
                return ResourceManager.GetString("BuildStep__Customize_the_footage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footage.
        /// </summary>
        public static string BuildStep__Footage {
            get {
                return ResourceManager.GetString("BuildStep__Footage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string BuildStep__Music {
            get {
                return ResourceManager.GetString("BuildStep__Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} spot{1} need{2} your own photo{1}.
        /// </summary>
        public static string BuildStep__Num_spots_need_your_own_photos {
            get {
                return ResourceManager.GetString("BuildStep__Num_spots_need_your_own_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your video.
        /// </summary>
        public static string BuildStep__Review_your_video {
            get {
                return ResourceManager.GetString("BuildStep__Review_your_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string BuildStep__Script {
            get {
                return ResourceManager.GetString("BuildStep__Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sect. {0} - appx. {1} into video, slot {2}.
        /// </summary>
        public static string BuildStep__Section_num_timing {
            get {
                return ResourceManager.GetString("BuildStep__Section_num_timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string BuildStep__Summary {
            get {
                return ResourceManager.GetString("BuildStep__Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        public static string BuildStep__Voice {
            get {
                return ResourceManager.GetString("BuildStep__Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your potential clients want to see you, so show us that big smile!.
        /// </summary>
        public static string BuildStep__Your_potential_clients_want_to_see_you {
            get {
                return ResourceManager.GetString("BuildStep__Your_potential_clients_want_to_see_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string Error_period {
            get {
                return ResourceManager.GetString("Error_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, {0} ({1}).
        /// </summary>
        public static string Login__Welcome {
            get {
                return ResourceManager.GetString("Login__Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back, {0}!.
        /// </summary>
        public static string Login__Welcome_back {
            get {
                return ResourceManager.GetString("Login__Welcome_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Photo.
        /// </summary>
        public static string Modals__Choose_a_Photo {
            get {
                return ResourceManager.GetString("Modals__Choose_a_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Navigation__Build {
            get {
                return ResourceManager.GetString("Navigation__Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new video.
        /// </summary>
        public static string Navigation__Create_a_new_video {
            get {
                return ResourceManager.GetString("Navigation__Create_a_new_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Navigation__Videos {
            get {
                return ResourceManager.GetString("Navigation__Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your video library.
        /// </summary>
        public static string Navigation__View_your_video_library {
            get {
                return ResourceManager.GetString("Navigation__View_your_video_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step.
        /// </summary>
        public static string Next_step {
            get {
                return ResourceManager.GetString("Next_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous step.
        /// </summary>
        public static string Previous_step {
            get {
                return ResourceManager.GetString("Previous_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PromoStudio.
        /// </summary>
        public static string PromoStudio {
            get {
                return ResourceManager.GetString("PromoStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending.
        /// </summary>
        public static string ScriptItemCategory__Ending {
            get {
                return ResourceManager.GetString("ScriptItemCategory__Ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        public static string ScriptItemCategory__Intro {
            get {
                return ResourceManager.GetString("ScriptItemCategory__Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string ScriptItemCategory__Logo {
            get {
                return ResourceManager.GetString("ScriptItemCategory__Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string ScriptItemCategory__Portfolio {
            get {
                return ResourceManager.GetString("ScriptItemCategory__Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ScriptItemCategory__Text {
            get {
                return ResourceManager.GetString("ScriptItemCategory__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ScriptItemCategory__Unknown {
            get {
                return ResourceManager.GetString("ScriptItemCategory__Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string ScriptItemType__Audio {
            get {
                return ResourceManager.GetString("ScriptItemType__Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ScriptItemType__Image {
            get {
                return ResourceManager.GetString("ScriptItemType__Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ScriptItemType__Text {
            get {
                return ResourceManager.GetString("ScriptItemType__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ScriptItemType__Unknown {
            get {
                return ResourceManager.GetString("ScriptItemType__Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string ScriptItemType__Video {
            get {
                return ResourceManager.GetString("ScriptItemType__Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending template.
        /// </summary>
        public static string StoryboardItemType__Ending {
            get {
                return ResourceManager.GetString("StoryboardItemType__Ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Template.
        /// </summary>
        public static string StoryboardItemType__Logo {
            get {
                return ResourceManager.GetString("StoryboardItemType__Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Template.
        /// </summary>
        public static string StoryboardItemType__Photo {
            get {
                return ResourceManager.GetString("StoryboardItemType__Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Video.
        /// </summary>
        public static string StoryboardItemType__Stock {
            get {
                return ResourceManager.GetString("StoryboardItemType__Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Template.
        /// </summary>
        public static string StoryboardItemType__Text {
            get {
                return ResourceManager.GetString("StoryboardItemType__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Audio.
        /// </summary>
        public static string VideoItemType__Stock_Audio {
            get {
                return ResourceManager.GetString("VideoItemType__Stock_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Video.
        /// </summary>
        public static string VideoItemType__Stock_Video {
            get {
                return ResourceManager.GetString("VideoItemType__Stock_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Video.
        /// </summary>
        public static string VideoItemType__Template_Video {
            get {
                return ResourceManager.GetString("VideoItemType__Template_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string VideoItemType__Unknown {
            get {
                return ResourceManager.GetString("VideoItemType__Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Over.
        /// </summary>
        public static string VideoItemType__Voice_Over {
            get {
                return ResourceManager.GetString("VideoItemType__Voice_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Voice Over.
        /// </summary>
        public static string VideoRenderStatus__Awaiting_Voice_Over {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Awaiting_Voice_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Builds In Progress.
        /// </summary>
        public static string VideoRenderStatus__Building {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Builds Completed.
        /// </summary>
        public static string VideoRenderStatus__Building_Completed {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Building_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Builds Completed - Preview.
        /// </summary>
        public static string VideoRenderStatus__Building_Completed_Preview {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Building_Completed_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Builds In Progress - Preview.
        /// </summary>
        public static string VideoRenderStatus__Building_Preview {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Building_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string VideoRenderStatus__Canceled {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string VideoRenderStatus__Completed {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string VideoRenderStatus__Pending {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render In Progress.
        /// </summary>
        public static string VideoRenderStatus__Rendering {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Rendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Completed.
        /// </summary>
        public static string VideoRenderStatus__Rendering_Completed {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Rendering_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Completed - Preview.
        /// </summary>
        public static string VideoRenderStatus__Rendering_Completed_Preview {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Rendering_Completed_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render In Progress - Preview.
        /// </summary>
        public static string VideoRenderStatus__Rendering_Preview {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Rendering_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string VideoRenderStatus__Unknown {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string VideoRenderStatus__Uploading {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading - Preview.
        /// </summary>
        public static string VideoRenderStatus__Uploading_Preview {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Uploading_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Over Completed, Pending Final Render.
        /// </summary>
        public static string VideoRenderStatus__Voice_Over_Completed {
            get {
                return ResourceManager.GetString("VideoRenderStatus__Voice_Over_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build a new video.
        /// </summary>
        public static string Videos__Build_a_new_video {
            get {
                return ResourceManager.GetString("Videos__Build_a_new_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading your videos....
        /// </summary>
        public static string Videos__Loading_your_videos_ellipsis {
            get {
                return ResourceManager.GetString("Videos__Loading_your_videos_ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no videos.
        /// </summary>
        public static string Videos__You_have_no_videos {
            get {
                return ResourceManager.GetString("Videos__You_have_no_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Videos.
        /// </summary>
        public static string Videos__Your_Videos {
            get {
                return ResourceManager.GetString("Videos__Your_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot; id=&quot;vidyard_embed_code_{0}&quot; src=&quot;//play.vidyard.com/{0}.js?v=3.1&amp;type=inline&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string Vidyard__InlineEmbed {
            get {
                return ResourceManager.GetString("Vidyard__InlineEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot; id=&quot;vidyard_embed_code_{0}&quot; src=&quot;//play.vidyard.com/{0}.js?v=3.1&amp;type=lightbox&quot;&gt;&lt;/script&gt;&lt;div&gt;&lt;div class=&quot;vidyard_wrapper&quot; onclick=&quot;fn_vidyard_{1}();&quot;&gt;&lt;img alt=&quot;{2}&quot; src=&quot;//play.vidyard.com/{0}.jpg&quot; width=&quot;360&quot; /&gt;&lt;div class = &quot;vidyard_play_button&quot;&gt;&lt;a href=&quot;javascript:void(0);&quot;&gt;&lt;/a&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;.
        /// </summary>
        public static string Vidyard__LightboxEmbed {
            get {
                return ResourceManager.GetString("Vidyard__LightboxEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://embed.vidyard.com/share/{0}.
        /// </summary>
        public static string Vidyard__PlayerUrl {
            get {
                return ResourceManager.GetString("Vidyard__PlayerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //embed.vidyard.com/embed/{0}/thumbnail.jpg.
        /// </summary>
        public static string Vidyard__ThumbnailUrl {
            get {
                return ResourceManager.GetString("Vidyard__ThumbnailUrl", resourceCulture);
            }
        }
    }
}
